import { readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';

const root = new URL('../', import.meta.url);
const app = readFileSync(new URL('app.js', root), 'utf8');
const html = readFileSync(new URL('index.html', root), 'utf8');
const css = readFileSync(new URL('app.css', root), 'utf8');
// Per-feature modules extracted from app.js / index.html / app.css. The
// static checks below look for feature markers; if a marker used to live
// inline but has moved into one of these modules we still want to find
// it, so include them in the search corpus.
const settings = readFileSync(new URL('settings.js', root), 'utf8');
const settingsCss = readFileSync(new URL('settings.css', root), 'utf8');
const files = readFileSync(new URL('files.js', root), 'utf8');
const filesCss = readFileSync(new URL('files.css', root), 'utf8');
const runtime = readFileSync(new URL('runtime.js', root), 'utf8');
const runtimeCss = readFileSync(new URL('runtime.css', root), 'utf8');
const deck = readFileSync(new URL('deck.js', root), 'utf8');
const deckCss = readFileSync(new URL('deck.css', root), 'utf8');
const launcher = readFileSync(new URL('launcher.js', root), 'utf8');
const launcherCss = readFileSync(new URL('launcher.css', root), 'utf8');
const panels = readFileSync(new URL('panels.js', root), 'utf8');
const normalize = readFileSync(new URL('app-normalize.js', root), 'utf8');
const workbenchExtension = readFileSync(new URL('wanix-workbench/dist/web/extension.js', root), 'utf8');

const syntax = spawnSync(process.execPath, ['--input-type=module', '--check'], { input: app, encoding: 'utf8' });
if (syntax.status !== 0) throw new Error(syntax.stderr || 'app.js syntax check failed');

for (const marker of ['FilesPanel', 'RuntimePanel', 'LandingPanel', 'DeckPanel', 'WorkbenchPanel', 'VmPanel', "component: 'deck'", "component: 'workbench'", "component: 'vm'", 'value="import"', 'data-system="allow-origins"']) {
  if (!app.includes(marker) && !html.includes(marker) && !settings.includes(marker) && !settingsCss.includes(marker) && !files.includes(marker) && !filesCss.includes(marker) && !runtime.includes(marker) && !runtimeCss.includes(marker) && !deck.includes(marker) && !deckCss.includes(marker) && !launcher.includes(marker) && !launcherCss.includes(marker) && !panels.includes(marker)) throw new Error(`Missing expected feature marker: ${marker}`);
}
if (!app.includes("workbench.setAttribute('raw', '')")) throw new Error('Workbench terminals must forward raw input.');
if (!app.includes("DEFAULT_WORKBENCH_ASSETS_URL = '/wanix-workbench'") && !settings.includes("DEFAULT_WORKBENCH_ASSETS_URL = '/wanix-workbench'") && !settingsCss.includes("DEFAULT_WORKBENCH_ASSETS_URL = '/wanix-workbench'") && !files.includes("DEFAULT_WORKBENCH_ASSETS_URL = '/wanix-workbench'") && !filesCss.includes("DEFAULT_WORKBENCH_ASSETS_URL = '/wanix-workbench'") && !runtime.includes("DEFAULT_WORKBENCH_ASSETS_URL = '/wanix-workbench'") && !runtimeCss.includes("DEFAULT_WORKBENCH_ASSETS_URL = '/wanix-workbench'") && !deck.includes("DEFAULT_WORKBENCH_ASSETS_URL = '/wanix-workbench'") && !deckCss.includes("DEFAULT_WORKBENCH_ASSETS_URL = '/wanix-workbench'") && !launcher.includes("DEFAULT_WORKBENCH_ASSETS_URL = '/wanix-workbench'") && !launcherCss.includes("DEFAULT_WORKBENCH_ASSETS_URL = '/wanix-workbench'") && !panels.includes("DEFAULT_WORKBENCH_ASSETS_URL = '/wanix-workbench'")) throw new Error('Workbench must default to the bundled static assets.');
if (!app.includes('LEGACY_DEFAULT_WORKBENCH_ASSETS_URL') && !settings.includes('LEGACY_DEFAULT_WORKBENCH_ASSETS_URL') && !settingsCss.includes('LEGACY_DEFAULT_WORKBENCH_ASSETS_URL') && !files.includes('LEGACY_DEFAULT_WORKBENCH_ASSETS_URL') && !filesCss.includes('LEGACY_DEFAULT_WORKBENCH_ASSETS_URL') && !runtime.includes('LEGACY_DEFAULT_WORKBENCH_ASSETS_URL') && !runtimeCss.includes('LEGACY_DEFAULT_WORKBENCH_ASSETS_URL') && !deck.includes('LEGACY_DEFAULT_WORKBENCH_ASSETS_URL') && !deckCss.includes('LEGACY_DEFAULT_WORKBENCH_ASSETS_URL') && !launcher.includes('LEGACY_DEFAULT_WORKBENCH_ASSETS_URL') && !launcherCss.includes('LEGACY_DEFAULT_WORKBENCH_ASSETS_URL') && !panels.includes('LEGACY_DEFAULT_WORKBENCH_ASSETS_URL')) throw new Error('Legacy Workbench asset defaults must migrate to the bundled assets.');
if (!app.includes('isLegacyWanixRuntimeUrl') && !settings.includes('isLegacyWanixRuntimeUrl') && !settingsCss.includes('isLegacyWanixRuntimeUrl') && !files.includes('isLegacyWanixRuntimeUrl') && !filesCss.includes('isLegacyWanixRuntimeUrl') && !runtime.includes('isLegacyWanixRuntimeUrl') && !runtimeCss.includes('isLegacyWanixRuntimeUrl') && !deck.includes('isLegacyWanixRuntimeUrl') && !deckCss.includes('isLegacyWanixRuntimeUrl') && !launcher.includes('isLegacyWanixRuntimeUrl') && !launcherCss.includes('isLegacyWanixRuntimeUrl') && !panels.includes('isLegacyWanixRuntimeUrl') && !normalize.includes('isLegacyWanixRuntimeUrl')) throw new Error('Workspaces pinning the Wanix runtime to commit hashes or @main must migrate to the current v<semver> release.');
if (!app.includes("panel.id.startsWith('workbench-')") && !panels.includes("panel.id.startsWith('workbench-')")) throw new Error('GearShell must focus the existing singleton Workbench panel.');
if (!app.includes("window.dispatchEvent(new Event('resize'))")) throw new Error('Workbench panels must forward Dockview resize events.');
if (!app.includes("vm.setAttribute('netdev', session.config.netdev)")) throw new Error('VM panels must forward their saved network configuration.');
if (!app.includes('DEFAULT_COLLAPSED_LAUNCHER_ITEMS') && !settings.includes('DEFAULT_COLLAPSED_LAUNCHER_ITEMS') && !settingsCss.includes('DEFAULT_COLLAPSED_LAUNCHER_ITEMS') && !files.includes('DEFAULT_COLLAPSED_LAUNCHER_ITEMS') && !filesCss.includes('DEFAULT_COLLAPSED_LAUNCHER_ITEMS') && !runtime.includes('DEFAULT_COLLAPSED_LAUNCHER_ITEMS') && !runtimeCss.includes('DEFAULT_COLLAPSED_LAUNCHER_ITEMS') && !deck.includes('DEFAULT_COLLAPSED_LAUNCHER_ITEMS') && !deckCss.includes('DEFAULT_COLLAPSED_LAUNCHER_ITEMS') && !launcher.includes('DEFAULT_COLLAPSED_LAUNCHER_ITEMS') && !launcherCss.includes('DEFAULT_COLLAPSED_LAUNCHER_ITEMS') && !panels.includes('DEFAULT_COLLAPSED_LAUNCHER_ITEMS')) throw new Error('Launcher needs configurable default collapsed items.');
if (!app.includes('launcher-more-toggle') && !settings.includes('launcher-more-toggle') && !settingsCss.includes('launcher-more-toggle') && !files.includes('launcher-more-toggle') && !filesCss.includes('launcher-more-toggle') && !runtime.includes('launcher-more-toggle') && !runtimeCss.includes('launcher-more-toggle') && !deck.includes('launcher-more-toggle') && !deckCss.includes('launcher-more-toggle') && !launcher.includes('launcher-more-toggle') && !launcherCss.includes('launcher-more-toggle') && !panels.includes('launcher-more-toggle')) throw new Error('Launcher needs a More control for collapsed items.');
if (!app.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !settings.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !settingsCss.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !files.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !filesCss.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !runtime.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !runtimeCss.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !deck.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !deckCss.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !launcher.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !launcherCss.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !panels.includes('DEFAULT_LAUNCHER_ITEM_ORDER') || !app.includes('normalizeLauncherOrder') && !settings.includes('normalizeLauncherOrder') && !settingsCss.includes('normalizeLauncherOrder') && !files.includes('normalizeLauncherOrder') && !filesCss.includes('normalizeLauncherOrder') && !runtime.includes('normalizeLauncherOrder') && !runtimeCss.includes('normalizeLauncherOrder') && !deck.includes('normalizeLauncherOrder') && !deckCss.includes('normalizeLauncherOrder') && !launcher.includes('normalizeLauncherOrder') && !launcherCss.includes('normalizeLauncherOrder') && !panels.includes('normalizeLauncherOrder')) throw new Error('Launcher must persist a complete item order.');
if (!html.includes('data-config-launcher-order') && !settings.includes('data-config-launcher-order') && !settingsCss.includes('data-config-launcher-order') && !files.includes('data-config-launcher-order') && !filesCss.includes('data-config-launcher-order') && !runtime.includes('data-config-launcher-order') && !runtimeCss.includes('data-config-launcher-order') && !deck.includes('data-config-launcher-order') && !deckCss.includes('data-config-launcher-order') && !launcher.includes('data-config-launcher-order') && !launcherCss.includes('data-config-launcher-order') && !panels.includes('data-config-launcher-order')) throw new Error('Settings must expose Launcher item ordering.');
if (!app.includes('function LauncherOrderEditor') && !settings.includes('function LauncherOrderEditor')) throw new Error('Launcher layout must combine ordering and visibility controls.');
if (!app.includes('setCollapsed') && !settings.includes('setCollapsed')) throw new Error('Launcher layout must combine ordering and visibility controls.');
if (!app.includes('onDragStart:') && !settings.includes('onDragStart:') && !settingsCss.includes('onDragStart:') && !files.includes('onDragStart:') && !filesCss.includes('onDragStart:') && !runtime.includes('onDragStart:') && !runtimeCss.includes('onDragStart:') && !deck.includes('onDragStart:') && !deckCss.includes('onDragStart:') && !launcher.includes('onDragStart:') && !launcherCss.includes('onDragStart:') && !panels.includes('onDragStart:') || !app.includes('EyeOff') && !settings.includes('EyeOff') && !settingsCss.includes('EyeOff') && !files.includes('EyeOff') && !filesCss.includes('EyeOff') && !runtime.includes('EyeOff') && !runtimeCss.includes('EyeOff') && !deck.includes('EyeOff') && !deckCss.includes('EyeOff') && !launcher.includes('EyeOff') && !launcherCss.includes('EyeOff') && !panels.includes('EyeOff') || !app.includes('Open by default') && !settings.includes('Open by default') && !settingsCss.includes('Open by default') && !files.includes('Open by default') && !filesCss.includes('Open by default') && !runtime.includes('Open by default') && !runtimeCss.includes('Open by default') && !deck.includes('Open by default') && !deckCss.includes('Open by default') && !launcher.includes('Open by default') && !launcherCss.includes('Open by default') && !panels.includes('Open by default')) throw new Error('Launcher layout must support drag, visibility icons, and default startup.');
if (!app.includes("src: '/bonsai/'") && !settings.includes("src: '/bonsai/'") && !settingsCss.includes("src: '/bonsai/'") && !files.includes("src: '/bonsai/'") && !filesCss.includes("src: '/bonsai/'") && !runtime.includes("src: '/bonsai/'") && !runtimeCss.includes("src: '/bonsai/'") && !deck.includes("src: '/bonsai/'") && !deckCss.includes("src: '/bonsai/'") && !launcher.includes("src: '/bonsai/'") && !launcherCss.includes("src: '/bonsai/'") && !panels.includes("src: '/bonsai/'") || !app.includes("label: 'Bonsai 27B'") && !settings.includes("label: 'Bonsai 27B'") && !settingsCss.includes("label: 'Bonsai 27B'") && !files.includes("label: 'Bonsai 27B'") && !filesCss.includes("label: 'Bonsai 27B'") && !runtime.includes("label: 'Bonsai 27B'") && !runtimeCss.includes("label: 'Bonsai 27B'") && !deck.includes("label: 'Bonsai 27B'") && !deckCss.includes("label: 'Bonsai 27B'") && !launcher.includes("label: 'Bonsai 27B'") && !launcherCss.includes("label: 'Bonsai 27B'") && !panels.includes("label: 'Bonsai 27B'")) throw new Error('Launcher must offer Bonsai 27B from the bundled Bonsai app.');
if (!app.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !settings.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !settingsCss.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !files.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !filesCss.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !runtime.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !runtimeCss.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !deck.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !deckCss.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !launcher.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !launcherCss.includes('DEFAULT_LAUNCHER_ITEM_ORDER') && !panels.includes('DEFAULT_LAUNCHER_ITEM_ORDER') || !app.includes("'bonsai'") && !settings.includes("'bonsai'") && !settingsCss.includes("'bonsai'") && !files.includes("'bonsai'") && !filesCss.includes("'bonsai'") && !runtime.includes("'bonsai'") && !runtimeCss.includes("'bonsai'") && !deck.includes("'bonsai'") && !deckCss.includes("'bonsai'") && !launcher.includes("'bonsai'") && !launcherCss.includes("'bonsai'") && !panels.includes("'bonsai'")) throw new Error('Launcher layout must include Bonsai 27B.');
if (!app.includes("import WebPet from './web-pet/index.js'") && !settings.includes("import WebPet from './web-pet/index.js'") && !settingsCss.includes("import WebPet from './web-pet/index.js'") && !files.includes("import WebPet from './web-pet/index.js'") && !filesCss.includes("import WebPet from './web-pet/index.js'") && !runtime.includes("import WebPet from './web-pet/index.js'") && !runtimeCss.includes("import WebPet from './web-pet/index.js'") && !deck.includes("import WebPet from './web-pet/index.js'") && !deckCss.includes("import WebPet from './web-pet/index.js'") && !launcher.includes("import WebPet from './web-pet/index.js'") && !launcherCss.includes("import WebPet from './web-pet/index.js'") && !panels.includes("import WebPet from './web-pet/index.js'")) throw new Error('Wagi Dog must use the bundled web-pet runtime.');
if (!app.includes('new WebPet()') && !panels.includes('new WebPet()')) throw new Error('GearShell must start the Wagi Dog web pet when enabled.');
if (!html.includes('href="web-pet/web-pet.css"') && !settings.includes('href="web-pet/web-pet.css"') && !settingsCss.includes('href="web-pet/web-pet.css"') && !files.includes('href="web-pet/web-pet.css"') && !filesCss.includes('href="web-pet/web-pet.css"') && !runtime.includes('href="web-pet/web-pet.css"') && !runtimeCss.includes('href="web-pet/web-pet.css"') && !deck.includes('href="web-pet/web-pet.css"') && !deckCss.includes('href="web-pet/web-pet.css"') && !launcher.includes('href="web-pet/web-pet.css"') && !launcherCss.includes('href="web-pet/web-pet.css"') && !panels.includes('href="web-pet/web-pet.css"')) throw new Error('GearShell must load the web-pet stylesheet.');
if (!app.includes('wagiDogEnabled: config?.wagiDogEnabled !== false') && !settings.includes('wagiDogEnabled: config?.wagiDogEnabled !== false') && !settingsCss.includes('wagiDogEnabled: config?.wagiDogEnabled !== false') && !files.includes('wagiDogEnabled: config?.wagiDogEnabled !== false') && !filesCss.includes('wagiDogEnabled: config?.wagiDogEnabled !== false') && !runtime.includes('wagiDogEnabled: config?.wagiDogEnabled !== false') && !runtimeCss.includes('wagiDogEnabled: config?.wagiDogEnabled !== false') && !deck.includes('wagiDogEnabled: config?.wagiDogEnabled !== false') && !deckCss.includes('wagiDogEnabled: config?.wagiDogEnabled !== false') && !launcher.includes('wagiDogEnabled: config?.wagiDogEnabled !== false') && !launcherCss.includes('wagiDogEnabled: config?.wagiDogEnabled !== false') && !panels.includes('wagiDogEnabled: config?.wagiDogEnabled !== false')) throw new Error('Wagi Dog must default to enabled for existing workspaces.');
if (!html.includes('data-config="wagi-dog-enabled"') && !settings.includes('data-config="wagi-dog-enabled"') && !settingsCss.includes('data-config="wagi-dog-enabled"') && !files.includes('data-config="wagi-dog-enabled"') && !filesCss.includes('data-config="wagi-dog-enabled"') && !runtime.includes('data-config="wagi-dog-enabled"') && !runtimeCss.includes('data-config="wagi-dog-enabled"') && !deck.includes('data-config="wagi-dog-enabled"') && !deckCss.includes('data-config="wagi-dog-enabled"') && !launcher.includes('data-config="wagi-dog-enabled"') && !launcherCss.includes('data-config="wagi-dog-enabled"') && !panels.includes('data-config="wagi-dog-enabled"')) throw new Error('Settings must expose the Wagi Dog toggle.');
if (!app.includes("'aria-checked': wagiDogEnabled") && !settings.includes("'aria-checked': wagiDogEnabled") && !settingsCss.includes("'aria-checked': wagiDogEnabled") && !files.includes("'aria-checked': wagiDogEnabled") && !filesCss.includes("'aria-checked': wagiDogEnabled") && !runtime.includes("'aria-checked': wagiDogEnabled") && !runtimeCss.includes("'aria-checked': wagiDogEnabled") && !deck.includes("'aria-checked': wagiDogEnabled") && !deckCss.includes("'aria-checked': wagiDogEnabled") && !launcher.includes("'aria-checked': wagiDogEnabled") && !launcherCss.includes("'aria-checked': wagiDogEnabled") && !panels.includes("'aria-checked': wagiDogEnabled")) throw new Error('The panel menu must expose the Wagi Dog toggle.');
if (!app.includes('TERMINAL_PRESET_ICON_OPTIONS') && !settings.includes('TERMINAL_PRESET_ICON_OPTIONS') && !settingsCss.includes('TERMINAL_PRESET_ICON_OPTIONS') && !files.includes('TERMINAL_PRESET_ICON_OPTIONS') && !filesCss.includes('TERMINAL_PRESET_ICON_OPTIONS') && !runtime.includes('TERMINAL_PRESET_ICON_OPTIONS') && !runtimeCss.includes('TERMINAL_PRESET_ICON_OPTIONS') && !deck.includes('TERMINAL_PRESET_ICON_OPTIONS') && !deckCss.includes('TERMINAL_PRESET_ICON_OPTIONS') && !launcher.includes('TERMINAL_PRESET_ICON_OPTIONS') && !launcherCss.includes('TERMINAL_PRESET_ICON_OPTIONS') && !panels.includes('TERMINAL_PRESET_ICON_OPTIONS')) throw new Error('Terminal presets need configurable Lucide icons.');
if (!html.includes('data-terminal-profile-editor') && !settings.includes('data-terminal-profile-editor') && !settingsCss.includes('data-terminal-profile-editor') && !files.includes('data-terminal-profile-editor') && !filesCss.includes('data-terminal-profile-editor') && !runtime.includes('data-terminal-profile-editor') && !runtimeCss.includes('data-terminal-profile-editor') && !deck.includes('data-terminal-profile-editor') && !deckCss.includes('data-terminal-profile-editor') && !launcher.includes('data-terminal-profile-editor') && !launcherCss.includes('data-terminal-profile-editor') && !panels.includes('data-terminal-profile-editor')) throw new Error('Settings must expose the Terminal preset editor.');
if (!app.includes('icons as LucideIcons') || !app.includes('Object.entries(LucideIcons)')) throw new Error('Terminal preset icons must cover the complete Lucide catalog.');
if (!app.includes('TerminalPresetIconPicker') && !settings.includes('TerminalPresetIconPicker') && !settingsCss.includes('TerminalPresetIconPicker') && !files.includes('TerminalPresetIconPicker') && !filesCss.includes('TerminalPresetIconPicker') && !runtime.includes('TerminalPresetIconPicker') && !runtimeCss.includes('TerminalPresetIconPicker') && !deck.includes('TerminalPresetIconPicker') && !deckCss.includes('TerminalPresetIconPicker') && !launcher.includes('TerminalPresetIconPicker') && !launcherCss.includes('TerminalPresetIconPicker') && !panels.includes('TerminalPresetIconPicker') || !app.includes('terminal-profile-icon-catalog') && !settings.includes('terminal-profile-icon-catalog') && !settingsCss.includes('terminal-profile-icon-catalog') && !files.includes('terminal-profile-icon-catalog') && !filesCss.includes('terminal-profile-icon-catalog') && !runtime.includes('terminal-profile-icon-catalog') && !runtimeCss.includes('terminal-profile-icon-catalog') && !deck.includes('terminal-profile-icon-catalog') && !deckCss.includes('terminal-profile-icon-catalog') && !launcher.includes('terminal-profile-icon-catalog') && !launcherCss.includes('terminal-profile-icon-catalog') && !panels.includes('terminal-profile-icon-catalog') || !app.includes('terminal-profile-icon-pagination') && !settings.includes('terminal-profile-icon-pagination') && !settingsCss.includes('terminal-profile-icon-pagination') && !files.includes('terminal-profile-icon-pagination') && !filesCss.includes('terminal-profile-icon-pagination') && !runtime.includes('terminal-profile-icon-pagination') && !runtimeCss.includes('terminal-profile-icon-pagination') && !deck.includes('terminal-profile-icon-pagination') && !deckCss.includes('terminal-profile-icon-pagination') && !launcher.includes('terminal-profile-icon-pagination') && !launcherCss.includes('terminal-profile-icon-pagination') && !panels.includes('terminal-profile-icon-pagination')) throw new Error('Terminal preset icons need a searchable, paginated picker.');
if (!(app.includes('catalogColumns * 3') || settings.includes('catalogColumns * 3')) || !(app.includes('ResizeObserver(updateColumns)') || settings.includes('ResizeObserver(updateColumns)'))) throw new Error('Terminal preset paging must fill three responsive icon rows.');
if (!app.includes('terminalProfileOrder') && !settings.includes('terminalProfileOrder') && !settingsCss.includes('terminalProfileOrder') && !files.includes('terminalProfileOrder') && !filesCss.includes('terminalProfileOrder') && !runtime.includes('terminalProfileOrder') && !runtimeCss.includes('terminalProfileOrder') && !deck.includes('terminalProfileOrder') && !deckCss.includes('terminalProfileOrder') && !launcher.includes('terminalProfileOrder') && !launcherCss.includes('terminalProfileOrder') && !panels.includes('terminalProfileOrder') || !app.includes('function normalizeTerminalProfileOrder') && !settings.includes('function normalizeTerminalProfileOrder') && !settingsCss.includes('function normalizeTerminalProfileOrder') && !files.includes('function normalizeTerminalProfileOrder') && !filesCss.includes('function normalizeTerminalProfileOrder') && !runtime.includes('function normalizeTerminalProfileOrder') && !runtimeCss.includes('function normalizeTerminalProfileOrder') && !deck.includes('function normalizeTerminalProfileOrder') && !deckCss.includes('function normalizeTerminalProfileOrder') && !launcher.includes('function normalizeTerminalProfileOrder') && !launcherCss.includes('function normalizeTerminalProfileOrder') && !panels.includes('function normalizeTerminalProfileOrder')) throw new Error('Terminal presets need persisted ordering.');
if (!app.includes('terminal-profile-handle') && !settings.includes('terminal-profile-handle') && !settingsCss.includes('terminal-profile-handle') && !files.includes('terminal-profile-handle') && !filesCss.includes('terminal-profile-handle') && !runtime.includes('terminal-profile-handle') && !runtimeCss.includes('terminal-profile-handle') && !deck.includes('terminal-profile-handle') && !deckCss.includes('terminal-profile-handle') && !launcher.includes('terminal-profile-handle') && !launcherCss.includes('terminal-profile-handle') && !panels.includes('terminal-profile-handle') || !app.includes('onDragStart:') && !settings.includes('onDragStart:') && !settingsCss.includes('onDragStart:') && !files.includes('onDragStart:') && !filesCss.includes('onDragStart:') && !runtime.includes('onDragStart:') && !runtimeCss.includes('onDragStart:') && !deck.includes('onDragStart:') && !deckCss.includes('onDragStart:') && !launcher.includes('onDragStart:') && !launcherCss.includes('onDragStart:') && !panels.includes('onDragStart:')) throw new Error('Terminal presets need drag reorder controls.');
if (!app.includes("user,type=virtio,relay_url=${wispUrl}") && !settings.includes("user,type=virtio,relay_url=${wispUrl}") && !settingsCss.includes("user,type=virtio,relay_url=${wispUrl}") && !files.includes("user,type=virtio,relay_url=${wispUrl}") && !filesCss.includes("user,type=virtio,relay_url=${wispUrl}") && !runtime.includes("user,type=virtio,relay_url=${wispUrl}") && !runtimeCss.includes("user,type=virtio,relay_url=${wispUrl}") && !deck.includes("user,type=virtio,relay_url=${wispUrl}") && !deckCss.includes("user,type=virtio,relay_url=${wispUrl}") && !launcher.includes("user,type=virtio,relay_url=${wispUrl}") && !launcherCss.includes("user,type=virtio,relay_url=${wispUrl}") && !panels.includes("user,type=virtio,relay_url=${wispUrl}")) throw new Error('VM settings must derive v86\'s native Wisp relay argument.');
if (!app.includes("user,type=virtio,relay_url=fetch") && !settings.includes("user,type=virtio,relay_url=fetch") && !settingsCss.includes("user,type=virtio,relay_url=fetch") && !files.includes("user,type=virtio,relay_url=fetch") && !filesCss.includes("user,type=virtio,relay_url=fetch") && !runtime.includes("user,type=virtio,relay_url=fetch") && !runtimeCss.includes("user,type=virtio,relay_url=fetch") && !deck.includes("user,type=virtio,relay_url=fetch") && !deckCss.includes("user,type=virtio,relay_url=fetch") && !launcher.includes("user,type=virtio,relay_url=fetch") && !launcherCss.includes("user,type=virtio,relay_url=fetch") && !panels.includes("user,type=virtio,relay_url=fetch")) throw new Error('VM settings must derive v86\'s native fetch relay argument.');
if (!html.includes('data-config-value="vmWispUrl"') && !settings.includes('data-config-value="vmWispUrl"') && !settingsCss.includes('data-config-value="vmWispUrl"') && !files.includes('data-config-value="vmWispUrl"') && !filesCss.includes('data-config-value="vmWispUrl"') && !runtime.includes('data-config-value="vmWispUrl"') && !runtimeCss.includes('data-config-value="vmWispUrl"') && !deck.includes('data-config-value="vmWispUrl"') && !deckCss.includes('data-config-value="vmWispUrl"') && !launcher.includes('data-config-value="vmWispUrl"') && !launcherCss.includes('data-config-value="vmWispUrl"') && !panels.includes('data-config-value="vmWispUrl"')) throw new Error('Settings must expose the Wisp server URL.');
if (!app.includes('wanix-extras@0.4.0-rc2/dist/v86.tgz') && !settings.includes('wanix-extras@0.4.0-rc2/dist/v86.tgz') && !settingsCss.includes('wanix-extras@0.4.0-rc2/dist/v86.tgz') && !files.includes('wanix-extras@0.4.0-rc2/dist/v86.tgz') && !filesCss.includes('wanix-extras@0.4.0-rc2/dist/v86.tgz') && !runtime.includes('wanix-extras@0.4.0-rc2/dist/v86.tgz') && !runtimeCss.includes('wanix-extras@0.4.0-rc2/dist/v86.tgz') && !deck.includes('wanix-extras@0.4.0-rc2/dist/v86.tgz') && !deckCss.includes('wanix-extras@0.4.0-rc2/dist/v86.tgz') && !launcher.includes('wanix-extras@0.4.0-rc2/dist/v86.tgz') && !launcherCss.includes('wanix-extras@0.4.0-rc2/dist/v86.tgz') && !panels.includes('wanix-extras@0.4.0-rc2/dist/v86.tgz')) throw new Error('VMs must default to the public v86 archive with built-in Wisp support.');
if (!app.includes('isLegacyVmBackendUrl') && !settings.includes('isLegacyVmBackendUrl') && !settingsCss.includes('isLegacyVmBackendUrl') && !files.includes('isLegacyVmBackendUrl') && !filesCss.includes('isLegacyVmBackendUrl') && !runtime.includes('isLegacyVmBackendUrl') && !runtimeCss.includes('isLegacyVmBackendUrl') && !deck.includes('isLegacyVmBackendUrl') && !deckCss.includes('isLegacyVmBackendUrl') && !launcher.includes('isLegacyVmBackendUrl') && !launcherCss.includes('isLegacyVmBackendUrl') && !panels.includes('isLegacyVmBackendUrl') && !normalize.includes('isLegacyVmBackendUrl')) throw new Error('Workspaces pinned to the commit-hash custom v86 archive must migrate to the semver-pinned public archive.');
if (!html.includes('Workbench assets URL or path') && !settings.includes('Workbench assets URL or path') && !settingsCss.includes('Workbench assets URL or path') && !files.includes('Workbench assets URL or path') && !filesCss.includes('Workbench assets URL or path') && !runtime.includes('Workbench assets URL or path') && !runtimeCss.includes('Workbench assets URL or path') && !deck.includes('Workbench assets URL or path') && !deckCss.includes('Workbench assets URL or path') && !launcher.includes('Workbench assets URL or path') && !launcherCss.includes('Workbench assets URL or path') && !panels.includes('Workbench assets URL or path')) throw new Error('Workbench asset settings must accept local paths.');
if (!html.match(/src="app\.js\?v=[\d.]+"/)) throw new Error('index.html must cache-bust app.js');
if (!(css.includes('.files-panel') || filesCss.includes('.files-panel')) || !(css.includes('.runtime-panel') || runtimeCss.includes('.runtime-panel'))) throw new Error('Missing panel styles');
if (!css.includes('.workbench-session .explorer-folders-view .monaco-icon-label::before')) throw new Error('Missing scoped Workbench file icon spacing fix.');
if (!css.includes('.monaco-tl-twistie + .monaco-tl-contents > .monaco-icon-label.folder-icon')) throw new Error('Missing scoped Workbench folder label spacing fix.');
if (!css.includes('.monaco-list-row[aria-level]:not([aria-level="1"]) .monaco-tl-twistie') || !css.includes('translateX(5px)')) throw new Error('Nested Workbench tree controls must clear their indent guides.');
if (!css.includes('.monaco-list-row[aria-level]:not([aria-level="1"]) .indent-guide') || !css.includes('translateX(-4px)')) throw new Error('Nested Workbench indent guides must remain offset from child controls.');
if (css.includes('.workbench-session .monaco-tl-twistie')) throw new Error('GearShell must not override Workbench disclosure geometry.');
if (!workbenchExtension.includes('bind #task/self/term/winch winch')) throw new Error('Workbench terminals must mount their resize signal through the task namespace.');
if (!workbenchExtension.includes('setDimensions: async (dimensions')) throw new Error('Workbench terminals must forward VS Code resize events.');

console.log('Static verification passed.');
