#!/bin/busybox sh
case "$1" in
  bound|renew)
    /bin/busybox ifconfig "$interface" "$ip" netmask "$subnet" 2>/dev/null
    /bin/busybox route add default gw "$router" 2>/dev/null
    if [ -n "$dns" ]; then
      for d in $dns; do echo "nameserver $d"; done > /etc/resolv.conf
    fi
    ;;
esac
